name: Deploy to FastComet

on:
  push:
    branches:
      - add-actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      LFTP_USER:  ${{ secrets.LFTP_USER }}
      LFTP_PASSWORD: ${{ secrets.LFTP_PASSWORD }}
      LFTP_HOST: ${{ secrets.LFTP_HOST }}
    steps:
    - name: Install lftp
      run: sudo apt install lftp
    - uses: actions/checkout@v2
    - name: Deploy
      run: lftp -e "set ftp:ssl-allow no; set ssl:check-hostname no; mirror -R --only-newer -F tasks/*; bye;" -u $LFTP_USER,$LFTP_PASSWORD $LFTP_HOST
